import Head from 'next/head';
import { signIn, useSession, signOut } from 'next-auth/client';
import { setProtectedView } from '../api/signIn';

export default function Home() {
	const [session] = useSession();

	return (
		<div className='min-h-screen'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			{session ? (
				<div>
					<p>Signed in as {session.user.email}</p>
					<p>Name {session.user.name}</p>
					<img src={session.user.image} alt={session.user.name} />
				</div>
			) : (
				<button onClick={signIn}>Sign in</button>
			)}
			<br />
			<button onClick={signOut}>Sign Out</button>
		</div>
	);
}

setProtectedView(Home);
